# Generated by Django 5.0.7 on 2024-07-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
