# Generated by Django 5.0.7 on 2024-07-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_name_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
